# Generated by Django 3.2.5 on 2022-04-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_investor_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='resume',
        ),
        migrations.AddField(
            model_name='investment',
            name='resume',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=None),
        ),
    ]
