# Generated by Django 3.2.5 on 2022-04-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220421_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='Shift',
        ),
    ]
