# Generated by Django 3.2.5 on 2022-04-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_investment_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
