# Generated by Django 3.2.5 on 2022-04-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220424_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='salary',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='type',
            new_name='typeofpos',
        ),
    ]
