# Generated by Django 3.2.5 on 2022-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_investment_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
