# Generated by Django 3.2.5 on 2022-04-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220424_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='cv',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
