# Generated by Django 3.2.5 on 2022-04-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_investor_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='resume',
        ),
    ]
